-- MySQL Script generated by MySQL Workbench
-- Mon Feb 26 21:23:25 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Opalo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Opalo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Opalo` ;
USE `Opalo` ;

-- -----------------------------------------------------
-- Table `Opalo`.`idea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Opalo`.`idea` (
  `ididea` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `idea` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ididea`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
